config/routes.rb
CongressWatch::Application.routes.draw do

  devise_for :users
  resources :legislators
  resources :pages
  resources :subjects

  root :to => "home#index"

  

end

app/models/page.rb
class Page < ActiveRecord::Base
	include HTTParty
	base_uri  'http://api.nytimes.com/svc/politics/v3/us/legislative/congress'
	format :xml
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected


  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :age << :gender << :city << :state << :image << :type
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@committees = Congress.committees
		@bills = Congress.bills('per_page' => 5)
		@floor_updates = Congress.floor_updates
	end
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController
  def index
    @zipcode = params[:zip] || "02134"
    @legislators = Congress.legislators_locate(@zipcode)
  end

  def new
  end

  def show
  end


  def create     
    @legislator = Legislator.new(zipcode_params)     
    if
      @legislator.save format.html { redirect_to @legislator, notice: 'Legislators were
        successfully created.' }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through. def person_params params.require(: person). permit(: first_name, :last_name) end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController   

	def index 
		@bill_bulk_data = Congress.bills_search(:query => "health care") 
		@response = Page.get('/113/house/members/current?api-key=6cfc49901eb5136c7537c705595f4f0d:13:63277080')   
	end


	def create          
		@page = Page.new(zipcode_params)          
		if @page.save format.html { redirect_to @page, notice: 'Pages were successfully created.' }
		end    
	end




end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }

      else
        format.html { render action: 'new' }
      end
    end
  end

end



  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
		<div class="row">
			<div class="col-md-4">
				<%= image_tag "2011_State_of_the_Union.jpg", :size => "380x285", :responsive => true %>
				<h3 class="text-center">Floor Updates</h3>
				<div style="overflow-y:scroll; height:400px;">
					<% @floor_updates['results'].each do |floor_update| %>
					<p><%= floor_update[:timestamp] %>: <%= floor_update[:update] %></p>
					<% end %>
				</div>
			</div>

			<div class="col-md-4">
				<%= image_tag "Civilrightsact1964.jpg", :size => "380x285", :responsive => true %>

				<h3 class="text-center">Bills</h3>
				<div style="overflow-y:scroll; height:400px;">
					<% @bills['results'].each do |bill| %>
					<p><%= bill[:bill_id] %>: <%= bill[:sponsor_id] %> <%= bill[:official_title] %></p>
					<% end %>
				</div>
			</div>

			<div class="col-md-4">
				<%= image_tag "Congress_Hall_committee_room_2.jpg", :size => "380x285", :responsive => true %>
				<h3 class="text-center">Active Committees</h3>
				<div style="overflow-y:scroll; height:400px;">
					<% @committees['results'].each do |committee| %>
					<p><%= committee[:chamber] %>: <%= committee[:committee_id] %> <%= committee[:name] %></p>
					<% end %>
				</div>
			</div>
		</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
	<button type="button" class="pull-right"><%= link_to 'Log Out',destroy_user_session_path, method: 'delete' %></button>
	<div class='pull-right'>
	
	<%= form_tag("/legislators/", method: "get") do %>
	<%= label_tag(:zip, "Enter Your Zip Code:") %>
	<%= text_field_tag(:zip) %>
	<%= submit_tag("Enter Zip") %>
	<% end %>
	</div> 

<% else %>
			<button type="button" class="pull-right"><%= link_to 'Sign Up', new_user_registration_path %></button><button type="button" class="pull-right"><%= link_to 'Log In', new_user_session_path %></button>
<% end %>

app/views/layouts/_news.html.erb
<%= "@floor_updates" %>

<%= "@bills" %>

<%= "@committees" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CongressWatch</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap -->
	<link href="css/bootstrap.min.css" rel="stylesheet" media="screen">

	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%#= stylesheet_link_tag    "legislator", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "legislator", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>
      <nav class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Congress Watch</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/users/sign_in"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            </ul>
            <%= render 'layouts/navbar' %>

          </div><!-- /.navbar-collapse -->
        </div>
      </nav>



      <header>
        <div class="container-fluid">
          <div class="jumbotron">
            <h1>Congress Watch</h1>
            <p>powered by the Sunlight Foundation API</p>
          </div>
        </div>
      </header>
      <div class="container">

        <%= yield %> 
      </div> 
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-4">&copy; 2013 Daniel Crews</div>
            <div class="col-md-4">
              <ul class="nav nav-pills">
                <li><a href="http://sunlightfoundation.com/">Sunlight Foundation</a></li>
                <li><a href="https://generalassemb.ly/">General Assembly</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>  



      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <script src="//code.jquery.com/jquery.js"></script>
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="js/bootstrap.min.js"></script>

  </body>
</html>

app/views/legislators/_form.html.erb
<%= form_tag("/legislators/", method: "get") do %>
<%= label_tag(:zip, "Enter Your Zip Code:") %>
<%= text_field_tag(:zip) %>
<%= submit_tag("Enter Zip") %>
<% end %> 

app/views/legislators/index.html.erb
<h1>Legislators in <%= @zipcode %></h1>

<% @legislators['results'].each do |legislator| %>
<% image = legislator[:bioguide_id].to_s %>
<% @twitter = legislator[:twitter_id].to_s %>

<div class="row-fluid">
	<div class="col-md-6" class="row-fluid">
		<%= image_tag "#{image}.jpg", :size => "200x250", :responsive => true %>
		<h3 class="text-center"><%= "#{legislator[:title]} #{legislator[:first_name]} #{legislator[:last_name]}" %></h3>
		<div style="overflow-y:scroll; height:400px;">
			<p><span class = "bold"><%= "State: "%></span><%="#{legislator[:state]}" %></p>
			<p><span class = "bold"><%= "Chamber: "%></span><%="#{legislator[:chamber]}" %></p>
			<p><span class = "bold"><%= "Term Start: "%></span><%="#{legislator[:term_start]}" %></p>
			<p><span class = "bold"><%= "Term End: "%></span><%="#{legislator[:term_end]}" %></p>
			<p><span class = "bold"><%= "Party: "%></span><%="#{legislator[:party]}" %></p>
			<p><span class = "bold"><%= "Website: "%></span><%= link_to "#{legislator[:website]}", legislator[:website] %></p>
			<p><span class = "bold"><%= "Contact Form: "%></span><%= link_to "#{legislator[:contact_form]}", legislator[:contact_form] %></p>
			<p><span class = "bold"><%= "Facebook_ID: " %></span><%= link_to "http://facebook.com/#{legislator[:facebook_id]}", "http://facebook.com/legislator[:facebook_id]" %></p>
			<p><span class = "bold"><%= "Twitter: " %></span><%= link_to "http://twitter.com/#{legislator[:twitter_id]}", "http://twitter.com/legislator[:twitter_id]" %></p>
			<p><span class = "bold"><%= "Phone: "%></span><%="#{legislator[:phone]}" %></p>
			<p><span class = "bold"><%= "Fax: "%></span><%="#{legislator[:fax]}" %></p>
			<p><span class = "bold"><%= "Birthday: "%></span><%="#{legislator[:birthday]}" %></p>
		</div>
	</div>	
</div>




<%# legislator.each do |key, value| %> 
<%#= "#{key.to_s} #{value.to_s}" %>
<%# end %>


<% end %>

app/views/legislators/new.html.erb
<h1> Your Legislators </h1>
<%= render 'form' %>
<%#= link_to 'Back', legislator_path %>

app/views/pages/index.html.erb
<%#= @bill_bulk_data.each_pair { |key, value| hash[key] = value.to_a } %>

<%# new_hash = @bill_bulk_data.results.inject({}) {|h, (key, value)| h[key] = value; h } %>

<%# newer_hash = new_hash.inject({}) {|h, (key, value)| h[key] = value; h }%>

<%# newest_hash = newer_hash.inject({}) {|h, (key, value)| h[key] = value; h } %>   
<%#= newest_hash %>

<%# first = @bill_bulk_data.each{|k,v| @bill_bulk_data[k]=*v} %>

<%# second  = first.collect { |k, v| v } %>

<%#= second.flatten %>

<%#= @response %>

<%#= xml_doc = Nokogiri::XML(@response) %>




<%# xml_doc = Nokogiri::XML('@response') %>
<%# unpack = @response.values_at('result_set') %>
<%# unpacked = [] %>
<%# further_unpacked = [] %>
<%# n = @response.length %>

<%# count=0 %>
<%# while count <= n do %>
<%# unpacked << @response.at(n) %>
<%# count = count + 1 %>
<%# end %>

<%# further_unpacked << unpacked.fetch(0) %>

<%=  @response %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>